version: "3.8"

services:
  db:
    #container_name: mysql
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3306:3306
    env_file:
      - ./.env_mysql
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql

  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - /home/kondo/Dockers/mysql_servaer_local/docker/workbench:/config
    ports:
      - 3300:3300
    cap_add:
      - IPC_LOCK
    restart: unless-stopped

  seq:
    image: datalust/seq:latest
    ports:
      - "8001:80"
      - "5341:5341"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ./docker/seq/data:/data

volumes:
  mysql-data:
    name: mysql-volume
